name: intl_phone_number_input
description: A simple and customizable flutter package for inputting phone number in intl / international format uses Google's libphonenumber.
version: 0.7.0+2
homepage: https://github.com/natintosh/intl-phone-number-input

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  libphonenumber: ^2.0.2
  equatable: ^2.0.3
  collection: ^1.15.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.16.5


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  assets:
    - assets/flags/
