name: intl_phone_number_input
description: A simple and customizable flutter package for inputting phone number in intl / international format uses Google's libphonenumber.
version: 0.7.5
homepage: https://github.com/natintosh/intl-phone-number-input

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  dlibphonenumber: ^1.1.32
  equatable: ^2.0.7
  collection: ^1.19.1

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  assets:
    - assets/flags/
